# Generated by Django 4.1 on 2023-01-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('txt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='date_modified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='time_modified',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
