# Generated by Django 4.1 on 2023-01-10 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('txt', '0002_alter_textdocument_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdocument',
            name='time_created',
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
