# Generated by Django 4.1 on 2023-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('txt', '0003_remove_textdocument_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdocument',
            name='time_modified',
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
