# Generated by Django 4.1 on 2023-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('txt', '0004_remove_textdocument_time_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
