# Generated by Django 4.1 on 2023-01-12 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('txt', '0006_alter_textdocument_content_mainfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainFolder',
        ),
    ]
